version: 0.0
Resources:
  - myApp:
      Type: AWS::EKS::Application
      Properties:
        Name: brain-tasks-app
        ClusterName: brain-tasks-cluster
        Namespace: default
        Files:
          - source: deployment.yaml
            destination: /tmp/deployment.yaml
          - source: service.yaml
            destination: /tmp/service.yaml
Hooks:
  BeforeInstall:
    - location: scripts/update-image.sh
      timeout: 300
  AfterInstall:
    - location: scripts/kubectl-apply.sh
      timeout: 300