version: 0.2
env:
  variables:
    APP_NAME: brain-tasks-app
phases:
  pre_build:
    commands:
      - echo "Logging in to ECR.."
      - BUILD_NUMBER=${CODEBUILD_BUILD_NUMBER}
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI/$APP_NAME
  build:
    commands:
      - echo "Building the Docker image..."
      - echo "Using build number $BUILD_NUMBER"
      - docker build -t $ECR_REPO_URI/$APP_NAME:$BUILD_NUMBER .
      - echo "Tagging the Docker image..."
      - docker tag $ECR_REPO_URI/$APP_NAME:$BUILD_NUMBER $ECR_REPO_URI/$APP_NAME:BUILD_NUMBER
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REPO_URI/$APP_NAME:$BUILD_NUMBER
      - echo "Updating deployment.yaml with ECR URI and tag..."
      - sed -i "s|REPO_URI_PLACEHOLDER|$ECR_REPO_URI/$APP_NAME|g" deployment.yaml
      - sed -i "s|TAG_PLACEHOLDER|$BUILD_NUMBER|g" deployment.yaml
artifacts:
  files:
    - appspec.yml
    - deployment.yaml
    - service.yaml
    - scripts/**/*