version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO_NAME: brain-tasks-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPO_URI=$(aws ecr describe-repositories --repository-names $ECR_REPO_NAME --query 'repositories[0].repositoryUri' --output text)
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 911167920418.dkr.ecr.ap-south-1.amazonaws.com $REPO_URI
  build:
    commands:
      - echo Building Docker image with build number $CODEBUILD_BUILD_NUMBER...
      - docker build -t $ECR_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $ECR_REPO_NAME:$CODEBUILD_BUILD_NUMBER $REPO_URI:$CODEBUILD_BUILD_NUMBER
      - docker tag $ECR_REPO_NAME:$CODEBUILD_BUILD_NUMBER $REPO_URI:latest
  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPO_URI:$CODEBUILD_BUILD_NUMBER
      - docker push $REPO_URI:latest
      - echo Writing image definitions file...
      - sed -i "s|<IMAGE_URI>|$REPO_URI:$CODEBUILD_BUILD_NUMBER|g" deployment.yaml
artifacts:
  files:
    - '**/*'
