version: 0.2
env:
  variables:
    ECR_REPO_URI: 911167920418.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app 
    APP_NAME: brain-tasks-app
phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - BUILD_NUMBER=${CODEBUILD_BUILD_NUMBER}
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 911167920418.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - echo "Using build number $BUILD_NUMBER"
      - docker build -t $ECR_REPO_URI:$BUILD_NUMBER .
      - echo "Tagging the Docker image..."
      - docker tag $ECR_REPO_URI:$BUILD_NUMBER $ECR_REPO_URI:BUILD_NUMBER
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REPO_URI:$BUILD_NUMBER
      - echo "Creating the build artifact for CodeDeploy..."
      - printf '[{"name":"brain-tasks-app-container","imageUri":"%s"}]' $ECR_REPO_URI:$BUILD_NUMBER > imagedefinitions.json
artifacts:
  files:
    - '**/*' 
