apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-tasks
  template:
    metadata:
      labels:
        app: brain-tasks
    spec:
      containers:
        - name: brain-tasks-container
          image: REPO_URI_PLACEHOLDER:TAG_PLACEHOLDER
          ports:
            - containerPort: 3000
