apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brain-tasks-cluster
  region: ap-south-1
  version: "1.32"

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
