apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<accountId>:role/<roleName>
      username: eks-codedeploy-user
      groups:
        - codedeploy-group